### ISSUE TITLE
allow configurable generators

### ISSUE THREAD

**Issue by stevesea** [stevesea/Adventuresmith#113]
Seems like...
generator could define input map
```
input:
  val1: defaultVal1
  val2: defaultVal2
  val3: defaultVal3
```

if that's there, GUI could display configure-glyph on generator button. only enabled for generators that have input config.
that map is saved in user's shared preferences as "GeneratorConfig.<gen-id>"
Generator.generate now takes optional param

possible generators SS&SS spell consequences, Perilous Wilds guarded treasure generator
