### ISSUE TITLE
make completely data-driven generator

### ISSUE THREAD

**Issue by stevesea** [stevesea/Adventuresmith#64]
could do something along the lines of:

```
---
config:
  name: <name of generator>
  id: <id of generator... namespace prefix(es) to support hierarchy>
templates:
  - "${form} ${element}"
  - "${adjective} ${element}"
tables:
  form: 
     - val1
     - val2
  element:
     - valA
     - valB
```

the rough algorithm would be:

1. pick a  template
1. iterate over the words in the template matching ${<thing>}
  * for each <thing>, look <thing> up in the tables map and randomly pick

unknowns:
* do jackson polymorphic deserialization to let tables either be List<String> or RangeMap?
* does <thing> need its own syntax? pick? pickN? 
* how to handle translations?
  * maybe have a separate file with a map of generator ids to resource prefixes. Look up the right table like in the existing app
* how to do hierarchy of generators?

short-term: 
* seems like this could be used for some of the simpler generators already implemented. (MR/FotF/FP, and some of the PW/SWN generators). So... work on a simple version of this soon

long-term: 
* logged separate ticket for long-term work https://github.com/stevesea/Adventuresmith/issues/65

**Comment by stevesea** [comment]
example data file:

```
---
# keywords in templates must appear as keys in the tables map of this
# file (or as keys in the tables of specified sibling files in this same directory
# see merged_siblings_tables)
#
# implementation notes:
# - the 'merged_sibling_tables' is a list of file prefixes which must be located
#   in the same directory as the current file.
#
# - templates are Mustache templates (specifically, jmustache). so, you can
#   probably do some strange and awful things with them. And, probably break the app.
#
# - the context passed to the template compiler is this file's table, plus any
#   tables defined in the sibling tables. Tables are applied to the context in
#   reverse order of entry in the 'siblings' table, and then this file's tables.
#
#   If there are any naming collisions, they'll be silently overriden in the above order.
#   Tables are _not_ merged.
#
templates:
- >
  Name: {{forename}} {{surname}}

  STR: {{3d6}} DEX: {{3d6}} WIL: {{3d6}}  HP: {{>1d6}}

  Appearance: {{appearance}}, {{appearance}}

  Personality: {{personality}}, {{personality}}

  Weapons: {{weapon}}, {{weapon}}

  Equipment: {{equipment}}, {{equipment}}, {{equipment}}

# a list of other input data files that should be loaded into the context.
# they _must_ be located next to this file
include_tables:
- names

# a dice list is optional. If used, it'll add dice keywords like the tables keywords to the template.
#   example:  {{3d6}}
#
# alternatively, you can use a partial
#   example:  {{>1d6}}
#
#   TODO: partial syntax will probably change to something like:
#       {{> dice: 1d6}}
#       {{> pick 3 appearance ,}}
dice:
- 3d6


# tables is a map of adventuresmith RangeMaps. In terms of YaML syntax, these are just
# lists of Strings. Overlapping ranges are not permitted and will be flagged as errors.
# Holes in the accumulated set of ranges should be avoided, but is not strictly enforced.
#
# examples:
#
#  the following two rangemaps  are equivalent
#
#    tables:
#       heritage_ex1:
#       - 1..3, human    # ranges should be of form X..Y, where X and Y are integers. and X<=Y
#       - 4, halfling    # ranges can be a single entry. this becomes range X..X
#       - dwarf          # or none.  This becomes X=last line's max+1 ... X..X
#       - 6, elf
#
#       heritage_ex2:
#       - human
#       - human
#       - human
#       - halfling
#       - dwarf
#       - elf
#
#
tables:
  personality:
  - Arrogant
  - Avant-Garde
  - Boastful
  - Bored
  - Bossy
  - Can-do
  - Chatterbox
  - Chirpy
  - Cryptic
  - Ditz
  - Egomaniac
  - Extravagant
  - Fast-talker
  - Flake
  - Flirtatious
  - Gossip
  - Hard-boiled
  - Hears voices
  - Hillbilly
  - Hothead
  - Iconoclast
  - Idealistic
  - Illiterate
  - Jerk
  - Klutz
  - Love-struck
  - Misanthrope
  - Mopey
  - Naïve
  - Nerd
  - No-nonsense
  - Obsessive
  - Orator
  - Overeducated
  - Paranoid
  - Pouty
  - Prickly
  - Proselytizer
  - Refined
  - Ruthless
  - Self-pitying
  - Serene
  - Slacker
  - Slimy
  - Slovenly
  - Snarky
  - Snitch
  - Snob
  - Sophist
  - Spacey
  - Thick
  - Toady
  - Twitchy
  - Vain
  - Vegan
  - Vengeful
  - Whiner
  - Wild Child
  - Wisecracking
  - World-weary
  appearance:
  - Acid Scars
  - Battle Scars
  - Boney hands
  - Braided Hair
  - Brawny
  - Broken Nose
  - Bulbous Nose
  - Burn Scars
  - Bushy Brows
  - Chiseled
  - Curly Hair
  - Dark Skin
  - Disfigured
  - Disheveled
  - Filthy
  - Gaunt
  - Gap-toothed
  - Grey Hair
  - Groomed
  - Hairless
  - Hawk Nose
  - Immense
  - Lantern Jaw
  - Limp
  - Long Hair
  - Loud Voice
  - Meat Hooks
  - Missing Ear
  - Missing Eye
  - Nine Fingers
  - Oily Skin
  - Pale Skin
  - Perfect Skin
  - Perfect Teeth
  - Perfumed
  - Pierced
  - Plump
  - Pockmarked
  - Pointed Chin
  - Rosy Cheek
  - Rotten Teeth
  - Scrubbed
  - Shaved Head
  - Shifty Eyes
  - Short
  - Slender
  - Slouched
  - Smelly
  - Smiling
  - Soft Voice
  - Squinty Eyes
  - Steely Gaze
  - Sunken Eyes
  - Sweaty
  - Tattooed
  - Towering
  - Unsmiling
  - Weathered
  - White Hair
  - Wild Hair
  weapon:
  - Ancient Spear (d6)
  - Arming Sword (d6)
  - Battered Halberd (d8)
  - Battleaxe (d8)
  - Bronze Dagger (d6)
  - Bronze-tip Spear (d6)
  - Carved Spear (d6)
  - Claymore (d8)
  - Crank Crossbow (d10)
  - Etched Glaive (d8)
  - Falchion (d8)
  - Flail (d8)
  - Gleaming Halberd (d8)
  - Hand Crossbow (d6)
  - Hatchet (d6)
  - Heirloom Glaive (d8)
  - Hunting Bow (d6)
  - Hunting Knife (d6)
  - Iron Club (d6)
  - Ivory Spear (d6)
  - Longbow (d8)
  - Maul (d8)
  - Messer (d8)
  - Morningstar (d8)
  - Obsidian Dagger (d6)
  - Painted Spear (d6)
  - Pull Crossbow (d10)
  - Quarterstaff (d6)
  - Rapier (d6)
  - Recurve Bow (d6)
  - Rusty Mace (d6)
  - Sling with bullets (d6)
  - Sling with stones (d6)
  - Spiked Club (d6)
  - Steel Dagger (d6)
  - Stone-tip Spear (d6)
  - Throwing Knives (d6)
  - War Bow (d8)
  - Warhammer (d8)
  - Woodman’s axe (d8)
  equipment:
  - Acid
  - Animal Scent
  - Antitoxin
  - Armor
  - Bear Trap
  - Bell
  - Blank Book
  - Bolt-Cutters
  - Caltrops
  - Pliers
  - Candle
  - Chain (10 ft.)
  - Chalk (10)
  - Copper Wire
  - Crowbar
  - Dice
  - Door Ram
  - Ether
  - Falcon
  - Fiddle
  - Fire Oil
  - Fishing Hook
  - Flashbomb
  - Glue
  - Grap. Hook
  - Grease
  - Hacksaw
  - Hammer
  - Hand Drill
  - Hog Holder
  - Hound
  - Hourglass
  - Incense
  - Lantern
  - Large Sack
  - Lens
  - Lock & Key
  - Lockpicks (5)
  - Lodestone
  - Manacles
  - Marbles
  - Mule
  - Net
  - Pen & Ink
  - Pickaxe
  - Poison
  - Pole (10 ft.)
  - Potion
  - Rat
  - Rum Bottle
  - Shovel
  - Smokebomb
  - Spikes (5)
  - Spyglass
  - Stake
  - Steel Mirror
  - Tent
  - Thick Gloves
  - Trumpet
  - Whistle


```
